---
main:
    subworkflows:
        - "GATK-genotype"
        # - "GATK-mutect2"
        # - "shearwater"
        # - "GATK-map"
        # - "GATK-bqsr"
        # - "alignstats"

path:
    gatk-container: "docker://broadinstitute/gatk"
    bioconductor-container: "docker://quay.io/\
                             biocontainers/bioconductor-deepsnv:\
                             1.28.0--r351hf484d3e_0"
    # working directory of Snakefile
    temp_dir: "/scratch"

    # directory to hold all output data
    data_root: "/tigress/AKEY/akey_vol2/GTExSomaticMutations"

    # # # MAPPING # # #
    fastq_input: "__DATA_ROOT__/original_fastq"
    fastq_R1: "__FASTQ_INPUT__/{id}_1.fastq.gz"
    fastq_R2: "__FASTQ_INPUT__/{id}_2.fastq.gz"

    mapping_base: "__DATA_ROOT__/mapping"
    ubam: "__MAPPING_BASE__/ubams/{id}.ubam"
    marked_bam: "__MAPPING_BASE__/marked_bam/{id}.marked.bam"
    marked_metric: "__MAPPING_BASE__/marked_bam/{id}.marked.metrics.txt"
    marked_fastq: "__MAPPING_BASE__/marked_fastq/{id}.marked.fastq"
    temp_mapped_bam: "__MAPPING_BASE__/mapped_bam/{id}.temp.bam"
    mapped_bam: "__MAPPING_BASE__/mapped_bam/{id}.mapped.bam"
    mapped_bai: "__MAPPING_BASE__/mapped_bam/{id}.mapped.bai"

    dedup_bam: "__MAPPING_BASE__/dedup_bam/{id}.dedup.bam"
    dedup_bai: "__MAPPING_BASE__/dedup_bam/{id}.dedup.bam.bai"
    dedup_metric: "__MAPPING_BASE__/dedup_bam/{id}.dupmetrics.txt"

    # # # BQSR # # #
    recal_bam: "__DATA_ROOT__/MapFastqs.nobackup/{id}.bqsr.bam"
    recal_table: "__DATA_ROOT__/MapFastqs.nobackup/{id}.{type}_bqsr.table"
    recal_covariates: "__DATA_ROOT__/MapFastqs.nobackup/{id}.bqsr.pdf"

    # # # GENOTYPE # # #
    # supplemental files for haplotype calling
    haplotype_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                          Design_Annotation_files/SureSelect_Chrom/\
                          S04380110_SureSelect_V5_target_regions\
                          _chr{chromosome}.bed"
    # haplotype_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
    #                     Design_Annotation_files/PrimaryTarget/Unpadded/\
    #                     IntFormat/primary_target_regions_chr{chromosome}.bed"
    1000G_dir: "/tigress/AKEY/akey_vol1/home/selinav/GTEx/\
                VariantCalling.nobackup/RawVariants/BP_resolution/\
                Supp1kg/Chr{chromosome}"

    name_map: "__DATA_ROOT__/genotype/maps/chr{chromosome}.map"
    haplotype_raw: "__DATA_ROOT__/genotype/haplotypes/chr{chromosome}/\
                       {id}.raw_variants.g.vcf"
    haplotype_idx: "__DATA_ROOT__/genotype/haplotypes/chr{chromosome}/\
                       {id}.raw_variants.g.vcf.idx"
    genomics_db: "__DATA_ROOT__/genotype/DB/chr{chromosome}"
    genotype_gvcf: "__DATA_ROOT__/genotype/genotype/chr{chromosome}.vcf.gz"
    genotype_tbi: "__DATA_ROOT__/genotype/genotype/chr{chromosome}.vcf.tbi"

    reference_bundle: "/tigress/AKEY/akey_vol1/home/selinav/\
                       References.nobackup/GATK_reference_bundle_b37"
    ref_hapmap: "__REFERENCE_BUNDLE__/hapmap_3.3.b37.vcf"
    ref_omni: "__REFERENCE_BUNDLE__/1000G_omni2.5.b37.vcf"
    ref_1000g: "__REFERENCE_BUNDLE__/1000G_phase1.snps.high_confidence.b37.vcf"
    ref_dbsnp: "__REFERENCE_BUNDLE__/dbsnp_138.b37.vcf"
    vqsr_recal: "__DATA_ROOT__/genotype/recal/chr{chromosome}.recal"
    vqsr_tranche: "__DATA_ROOT__/genotype/recal/chr{chromosome}.tranches"
    vqsr_vcf: "__DATA_ROOT__/genotype/recal/chr{chromosome}.vcf.gz"

    # # # MUTECT2 # # #
    sample_details: "/tigress/AKEY/akey_vol1/home/selinav/GTEx/\
                     SampInfo/sample_details.txt"
    sites_only: "__DATA_ROOT__/mutect2.nobackup/sites-only/{id}.vcf.gz"
    pon_list: "__DATA_ROOT__/mutect2.nobackup/pon/\
               {individual}.{center}.vcf.args"
    pon: "__DATA_ROOT__/mutect2.nobackup/pon/{individual}.{center}.vcf.gz"

    unfiltered_vcf: "__DATA_ROOT__/mutect2.nobackup/calls/{id}.vcf.gz"
    mutect_bam: "__DATA_ROOT__/mutect2.nobackup/calls/{id}.bam"
    germline_resource: "/tigress/AKEY/akey_vol1/home/selinav/\
                        References.nobackup/GATK_Mutect2_reference_bundle/\
                        af-only-gnomad.raw.sites.b37.vcf.gz"
    exome_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                      Design_Annotation_files/SureSelect_Human_All_Exon_V5/\
                      S04380110_SureSelect_V5_target_regions_allchr_XY.bed"

    filter_input: "__RECAL_BAM__"
    common_snps: "/tigress/AKEY/akey_vol1/home/selinav/References.nobackup/\
                  GATK_Mutect2_reference_bundle/small_exac_common_3_b37.vcf.gz"
    pileup: "__DATA_ROOT__/mutect2.nobackup/filtered/{id}_pileup.table"
    con_tab: "__DATA_ROOT__/mutect2.nobackup/filtered/{id}_contamination.table"
    filter_vcf: "__DATA_ROOT__/mutect2.nobackup/filtered/{id}_filtered.vcf.gz"
    filter_vcf_temp: "__DATA_ROOT__/mutect2.nobackup/filtered/filtered.temp"

    # # # ALIGNSTATS # # #
    # exe location
    alignstats: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                 src/alignstats/alignstats"
    alignstats_input: "__RECAL_BAM__"
    alignstats_output: "__DATA_ROOT__/alignstats/{id}.report.txt"
    alignstats_target: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                        Design_Annotation_files/PrimaryTarget/Unpadded/\
                        IntFormat/primary_target_regions_allchr_XY.bed"

    # Reference with index files
    ref_genome: "/tigress/AKEY/akey_vol1/home/selinav/\
                 References.nobackup/hs37d5.fa"

    shearwater_input: "__RECAL_BAM__"
    shearwater_region: "__HAPLOTYPE_INTERVALS__"
    shearwater_vcf: "__DATA_ROOT__/shearwater/{chromosome}.vcf.gz"

gatk:
    verbosity: "ERROR"
    FastqToSam:
        memory: "4G"
        options: "-PL=ILLUMINA"

    MergeSamFiles:
        memory: "4G"
        options: "-SO queryname"

    MarkIlluminaAdapters:
        memory: "4G"

    SamToFastq:
        memory: "7G"
        options: >
            --CLIPPING_ATTRIBUTE=XT
            --CLIPPING_ACTION=2
            --INTERLEAVE=true
            --NON_PF=true

    Bwa_Mem:
        options: "-M -t 2"

    MergeBamAlignment:
        memory: "7G"
        options: >
            --CREATE_INDEX=true
            --ADD_MATE_CIGAR=true
            --INCLUDE_SECONDARY_ALIGNMENTS=true
            --MAX_INSERTIONS_OR_DELETIONS=-1
            --PRIMARY_ALIGNMENT_STRATEGY=MostDistant
            --ATTRIBUTES_TO_RETAIN=XS

    MarkDuplicates:
        memory: "4G"

    BQSR:
        memory: "1G"
        known_sites:
            "--known-sites /tigress/AKEY/akey_vol1/home/selinav/\
            References.nobackup/GATK_reference_bundle_b37/dbsnp_138.b37.vcf
            --known-sites /tigress/AKEY/akey_vol1/home/selinav/\
            References.nobackup/GATK_reference_bundle_b37/\
            Mills_and_1000G_gold_standard.indels.b37.vcf.gz
            --known-sites /tigress/AKEY/akey_vol1/home/selinav/\
            References.nobackup/GATK_reference_bundle_b37/\
            1000G_phase1.indels.b37.vcf.gz"
        target_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                           Design_Annotation_files/\
                           SureSelect_Human_All_Exon_V5/\
                           S04380110_SureSelect_V5_target_regions_allchr_XY.bed"

    HaplotypeCaller:
        memory: "2G"
        options: >
            --interval-padding 150
            --emit-ref-confidence BP_RESOLUTION

    GenomicsDBImport:
        memory: "4G"
        options: >
            --batch-size 50

    GenotypeGVCFs:
        memory: "4G"
        options: >
            --use-new-qual-calculator
            --interval-padding 100

    Mutect2_Sites_Only:
        memory: "1G"
        options: >
            --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter

    CreateSomaticPanelOfNormals:
        memory: "8G"

    Mutect2_Calls:
        memory: "3G"
        options: >
            --af-of-alleles-not-in-resource 0.0000025
            --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter
            --interval-padding 100

    Mutect2_Filter:
        memory: "1G"
        options: >
            --interval-padding 100

    VariantRecalibrator:
        memory: "4G"
        options:
            "-tranche 100.0
            -tranche 99.9
            -tranche 99.5
            -tranche 99.0
            -tranche 98.5
            -tranche 98.0
            -tranche 97.5
            -tranche 97.0
            -nt 4
            -mode SNP
            -an QD
            -an MQ
            -an MQRankSum
            -an ReadPosRankSum
            -an FS
            -an SOR
            --resource hapmap,known=false,training=true,\
            truth=true,prior=15.0:{hapmap}
            --resource omni,known=false,training=true,\
            truth=true,prior=12.0:{omni}
            --resource 1000G,known=false,training=true,\
            truth=false,prior=10.0:{OKG}
            --resource dbsnp,known=true,training=false,\
            truth=false,prior=2.0:{dbsnp}"

    ApplyVQSR:
        memory: "4G"
        options: >
            -mode SNP
            --ts_filter_level 99.0

alignstats:
    options: >
        -p
        -P 2
