---
main:
    subworkflows:
        # - "GATK-map"
        # - "GATK-bqsr"
        # - "alignstats"
        # - "GATK-map-metrics"
        # - "GATK-genotype"
        # - "GATK-mutect2"
        # - "shearwater"
        - "igv_batch"

# center: "nwgc"
# center: "macrogen"
center: "all"

path:
    gatk-container: "docker://broadinstitute/gatk:4.1.0.0"
    gatk3-container: "docker://broadinstitute/gatk3:3.8-1"
    bioconductor-container: "docker://quay.io/\
                             biocontainers/bioconductor-deepsnv:\
                             1.28.0--r351hf484d3e_0"
    temp_dir: "/scratch"

    # directory to hold all result and input
    data_root: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/Results.nobackup"

    # Reference with index files
    ref_genome: "/tigress/AKEY/akey_vol1/home/selinav/\
                 References.nobackup/hs37d5.fa"

    reference_bundle: "/tigress/AKEY/akey_vol1/home/selinav/\
                       References.nobackup/GATK_reference_bundle_b37"
    ref_hapmap: "__REFERENCE_BUNDLE__/hapmap_3.3.b37.vcf"
    ref_omni: "__REFERENCE_BUNDLE__/1000G_omni2.5.b37.vcf"
    ref_1000g: "__REFERENCE_BUNDLE__/1000G_phase1.snps.high_confidence.b37.vcf"
    ref_indel: "__REFERENCE_BUNDLE__/1000G_phase1.indels.b37.vcf.ga"
    ref_dbsnp: "__REFERENCE_BUNDLE__/dbsnp_138.b37.vcf"
    ref_mills: "__REFERENCE_BUNDLE__/Mills_and_1000G_\
                gold_standard.indels.b37.vcf.gz"

    germline_resource: "/tigress/AKEY/akey_vol1/home/selinav/\
                        References.nobackup/GATK_Mutect2_reference_bundle/\
                        af-only-gnomad.raw.sites.b37.vcf.gz"

    common_snps: "/tigress/AKEY/akey_vol1/home/selinav/References.nobackup/\
                  GATK_Mutect2_reference_bundle/small_exac_common_3_b37.vcf.gz"


    # tabulated data containing information for each sample
    sample_details: "/tigress/AKEY/akey_vol1/home/selinav/GTEx/\
                     SampInfo/sample_details.txt"

    exome_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                      Enrichment_targets/\
                      union_nwgc_macrogen_allchr_XY.bed"
    # exome_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
    #                   Enrichment_targets/Macrogen/\
    #                   primary_target_regions_allchr_XY.bed"
    # exome_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
    #                   Enrichment_targets/NWGC/\
    #                   primary_target_regions_allchr_XY.bed

    # supplemental files for haplotype calling
    chrom_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
                      Enrichment_targets/Union_ByChrom/chr{chromosome}.bed"
    # chrom_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
    #                   Enrichment_targets/Macrogen/ByChrom/chr{chromosome}.bed"
    # chrom_intervals: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/\
    #                     Enrichment_targets/NWGC/MoreFiles/PrimaryTarget/\
    #                     Unpadded/IntFormat/\
    #                     primary_target_regions_chr{chromosome}.bed"

    1000G_dir: "/tigress/AKEY/akey_vol1/home/selinav/GTEx/\
                VariantCalling.nobackup/RawVariants/BP_resolution/\
                Supp1kg/Chr{chromosome}"

    recal_bam: "__DATA_ROOT__/bqsr/bams/{id}.bqsr.bam"

gatk:
    verbosity: "ERROR"
