main:
    subworkflows:
        - "GATK"
        - "alignstats"

path:
    container: "docker://broadinstitute/gatk"
    base: "/home/tcomi/projects/gtex-gatk4"
    temp_dir: "/scatch/"
    
    # directory to hold all data
    data_root: "/tigress/tcomi/gatk4devel"

    fastq_input: "__DATA_ROOT__/original_fastq"
    fastq_R1: "__FASTQ_INPUT__/{id}_1.fastq.gz"
    fastq_R2: "__FASTQ_INPUT__/{id}_2.fastq.gz"

    ubam: "__DATA_ROOT__/ubams/{id}.ubam"
    marked_bam: "__DATA_ROOT__/marked_bam/{id}.marked.bam"
    marked_metric: "__DATA_ROOT__/marked_bam/{id}.marked.metrics.txt"
    mapped_bam: "__DATA_ROOT__/mapped_bam/{id}.mapped.bam"

    dedup_bam: "__DATA_ROOT__/dedup_bam/{id}.dedup.bam"
    dedup_metric: "__DATA_ROOT__/dedup_bam/{id}.dupmetrics.txt"

    recal_bam: "__DATA_ROOT__/bqsr_recal/{id}.bqsr.bam"
    recal_table: "__DATA_ROOT__/bqsr_recal/{id}.{type}_bqsr.table"
    recal_covariates: "__DATA_ROOT__/bqsr_recal/{id}.bqsr.pdf"
        
    alignstats: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/src/alignstats/alignstats"
    alignstats_input: "__RECAL_BAM__"
    alignstats_output: "__DATA_ROOT__/alignstats/{id}.report.txt"
    alignstats_target: "/tigress/AKEY/akey_vol2/GTExSomaticMutations/Design_Annotation_files/PrimaryTarget/Unpadded/IntFormat/primary_target_regions_allchr_XY.bed"

    #References
    ref_genome: "/tigress/AKEY/akey_vol1/home/selinav/References.nobackup/hs37d5.fa"

gatk:
    verbosity: "ERROR"
    FastqToSam:
        memory: "4G"
        options: "-PL=ILLUMINA"

    MergeSamFiles:
        memory: "4G"
        options: "-SO queryname"

    MarkIlluminaAdapters:
        memory: "4G"

    SamToFastq:
        memory: "4G"
        options: >
            --CLIPPING_ATTRIBUTE=XT
            --CLIPPING_ACTION=2
            --INTERLEAVE=true
            --NON_PF=true

    Bwa_Mem:
        options: "-M -t 2"

    MergeBamAlignment:
        memory: "4G"
        options: >
            --CREATE_INDEX=true
            --ADD_MATE_CIGAR=true
            --INCLUDE_SECONDARY_ALIGNMENTS=true
            --MAX_INSERTIONS_OR_DELETIONS=-1
            --PRIMARY_ALIGNMENT_STRATEGY=MostDistant
            --ATTRIBUTES_TO_RETAIN=XS

    MarkDuplicates:
        memory: "4G"

    BQSR:
        memory: "1G"
        known_sites: >
            --known-sites /tigress/AKEY/akey_vol1/home/selinav/References.nobackup/GATK_reference_bundle_b37/dbsnp_138.b37.vcf
            --known-sites /tigress/AKEY/akey_vol1/home/selinav/References.nobackup/GATK_reference_bundle_b37/Mills_and_1000G_gold_standard.indels.b37.vcf.gz
            --known-sites /tigress/AKEY/akey_vol1/home/selinav/References.nobackup/GATK_reference_bundle_b37/1000G_phase1.indels.b37.vcf.gz
        target_intervals: /tigress/AKEY/akey_vol2/GTExSomaticMutations/Design_Annotation_files/SureSelect_Human_All_Exon_V5/S04380110_SureSelect_V5_target_regions_allchr_XY.bed

alignstats:
    options: >
        -p
        -P 2
